### ISSUE TITLE
Add light mode

### ISSUE THREAD

**Issue by harrylongia** [eraaxit/emoticon-suggestor#3]
- Although the website looks great, but a switch to change it to light mode would satisfy light mode lovers.

**Comment by eraaxit** [comment]
@ShivamWho Goodluck. Would you like to share basic approach how you will allow users to toggle between light and dark theme ?

**Comment by eraaxit** [comment]
> I'm gonna try using styled-components library

@ShivamWho We started this project so that beginners can understand how things work from scratch. So we are avoiding to use any third party library until it's requirement is very much important. Please go through CONTRIBUTING.md, once and then begin with work ahead. If you face any issue, let us know, we would be happy to help you :)

**Comment by ShivamWho** [comment]
ok, is there any other way i can make it

**Comment by harrylongia** [comment]
I would like to work on it. Please assign it to me

**Comment by eraaxit** [comment]
Fixed by #12
